#!/usr/bin/env bash

# Ensure that Docker is running...
if [ $? -ne 0 ]; then
    echo "Docker is not running."

    exit 1
fi

name=$1
if [ -z "$name" ]; then
 echo "The name of app to install is required e.g \"install app-example\""
 exit 1
fi

#docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v "$(pwd)":/opt -w /opt -it pollen-solutions/installer:latest bash -c "pollen new ${name}"
docker run --rm -v "$(pwd)":/opt -w /opt -it pollen-solutions/installer:latest $(id -u ${USER}) bash -c "/home/pollen/.composer/vendor/bin/pollen new ${name}"

cd ${name}
bin/bigfish
